# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: npm
    directory: /cli
    schedule:
      interval: daily

  - package-ecosystem: npm
    directory: /next
    schedule:
      interval: daily

  - package-ecosystem: pip
    directory: /platform
    schedule:
      interval: daily
