version: '3'

volumes:
  db:

services:
  agentgpt:
    image: ghcr.io/reworkd/agentgpt:main
    container_name: agentgpt
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - 3000:3000
    volumes:
      - db:/app/db
    restart: unless-stopped